USE [master]
GO
/****** Object:  Database [BugTracker]    Script Date: 07/05/2007 14:14:22 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'BugTracker')
DROP DATABASE [BugTracker]
GO
/****** Object:  Database [BugTracker]    Script Date: 07/05/2007 14:13:24 ******/
CREATE DATABASE [BugTracker] 
/*ON  PRIMARY 
( NAME = N'BugTracker', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Data\BugTracker.mdf' , SIZE = 120832KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'BugTracker_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Data\BugTracker_log.LDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
*/
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'BugTracker', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BugTracker].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [BugTracker] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BugTracker] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BugTracker] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BugTracker] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BugTracker] SET ARITHABORT OFF 
GO
ALTER DATABASE [BugTracker] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BugTracker] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BugTracker] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BugTracker] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BugTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BugTracker] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BugTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BugTracker] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BugTracker] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BugTracker] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BugTracker] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BugTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BugTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BugTracker] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BugTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BugTracker] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BugTracker] SET  READ_WRITE 
GO
ALTER DATABASE [BugTracker] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BugTracker] SET  MULTI_USER 
GO
ALTER DATABASE [BugTracker] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [BugTracker] SET DB_CHAINING OFF  